# Add aliases as they appear in the source CSVs.
United States: United States
USA: United States
Czechia: Czech Republic
Czech Republic: Czech Republic
Curacao: Curaçao
Curaçao: Curaçao
CuraÃ§ao: Curaçao
CuraÃƒÂ§ao: Curaçao
